
variables:
  BUILD_VERSION: 1.9.6
  BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
  VCS_REF: $(git describe --tags --always --dirty)

image: docker:stable-git

services:
  - name: docker:dind
    command: ["--experimental"]

before_script:
  - curl -fsSL https://github.com/docker/compose/releases/download/1.25.0/run.sh -o /usr/local/bin/docker-compose
  - chmod a+x /usr/local/bin/docker-compose
  - mkdir -p ~/.docker/cli-plugins
  - curl -fsSL https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64 --output ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use --driver docker-container
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin docker.io

.test:
  stage: test
  script:
    - docker pull --platform ${PLATFORM} ${CI_REGISTRY_IMAGE}:latest || true
    - docker buildx build --pull --cache-from ${CI_REGISTRY_IMAGE}:latest --platform ${PLATFORM} --tag ${DOCKERHUB_REPOSITORY} --load .
    - docker-compose up --abort-on-container-exit

linux/amd64:
  extends: .test
  variables:
    PLATFORM: linux/amd64

linux/arm64:
  extends: .test
  variables:
    PLATFORM: linux/arm64

linux/ppc64le:
  extends: .test
  variables:
    PLATFORM: linux/ppc64le

linux/s390x:
  extends: .test
  variables:
    PLATFORM: linux/s390x

linux/arm/v7:
  extends: .test
  variables:
    PLATFORM: linux/arm/v7

linux/arm/v6:
  extends: .test
  variables:
    PLATFORM: linux/arm/v6

deploy:
  stage: deploy
  script:
    - docker pull ${CI_REGISTRY_IMAGE}:latest || true
    - docker buildx build --pull --cache-from ${CI_REGISTRY_IMAGE}:latest --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6 --build-arg BUILD_DATE --build-arg BUILD_VERSION --build-arg VCS_REF --tag ${CI_REGISTRY_IMAGE}:${BUILD_VERSION} --tag ${CI_REGISTRY_IMAGE}:latest --tag docker.io/${DOCKERHUB_REPOSITORY}:${BUILD_VERSION} --tag docker.io/${DOCKERHUB_REPOSITORY}:latest --push .
    - docker run -v ${PWD}:/workspace -e DOCKERHUB_USERNAME -e DOCKERHUB_PASSWORD -e DOCKERHUB_REPOSITORY -e README_FILEPATH=/workspace/README.md peterevans/dockerhub-description
  timeout: 2 hours
  only:
    - master
