
variables:
  BUILD_VERSION: 1.9.6
  BUILD_DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
  VCS_REF: $(git describe --tags --always --dirty)

image: docker:stable-git

services:
  - name: docker:dind
    command: ["--experimental"]

before_script:
  - apk add --no-cache curl py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  - pip install docker-compose
  - export DOCKER_BUILDKIT=1
  - git clone git://github.com/docker/buildx /tmp/buildx
  - docker build --platform=local -o . /tmp/buildx
  - mkdir -p ~/.docker/cli-plugins
  - mv buildx ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use --driver docker-container
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
  - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin docker.io

.test:
  stage: test
  script:
    - docker buildx build --pull --platform ${PLATFORM} --tag ${DOCKERHUB_REPOSITORY} --cache-to type=local,dest=.cache/${PLATFORM} --load .
    - docker-compose up --abort-on-container-exit
  artifacts:
    paths:
      - .cache/${PLATFORM}
    expire_in: 1 hour


linux/amd64:
  extends: .test
  variables:
    PLATFORM: linux/amd64

linux/arm64:
  extends: .test
  variables:
    PLATFORM: linux/arm64

linux/ppc64le:
  extends: .test
  variables:
    PLATFORM: linux/ppc64le

linux/s390x:
  extends: .test
  variables:
    PLATFORM: linux/s390x

linux/arm/v7:
  extends: .test
  variables:
    PLATFORM: linux/arm/v7

linux/arm/v6:
  extends: .test
  variables:
    PLATFORM: linux/arm/v6

deploy:
  stage: deploy
  script:
    - |
      docker buildx build . --pull --push --platform linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6 \
      --cache-from type=local,src=.cache/linux/amd64 \
      --cache-from type=local,src=.cache/linux/arm64 \
      --cache-from type=local,src=.cache/linux/ppc64le \
      --cache-from type=local,src=.cache/linux/s390x \
      --cache-from type=local,src=.cache/linux/arm/v7 \
      --cache-from type=local,src=.cache/linux/arm/v6 \
      --build-arg BUILD_DATE \
      --build-arg BUILD_VERSION \
      --build-arg VCS_REF \
      --tag ${CI_REGISTRY_IMAGE}:${BUILD_VERSION} \
      --tag ${CI_REGISTRY_IMAGE}:latest \
      --tag docker.io/${DOCKERHUB_REPOSITORY}:${BUILD_VERSION} \
      --tag docker.io/${DOCKERHUB_REPOSITORY}:latest
    - docker run -v ${PWD}:/workspace -e DOCKERHUB_USERNAME -e DOCKERHUB_PASSWORD -e DOCKERHUB_REPOSITORY -e README_FILEPATH=/workspace/README.md peterevans/dockerhub-description
  timeout: 2 hours
  only:
    - master
