
buildx:
  image: docker:stable-git
  stage: .pre
  services:
    - docker:dind
  variables:
    GIT_STRATEGY: none
  before_script: []
  script:
    - export DOCKER_BUILDKIT=1
    - git clone git://github.com/docker/buildx /tmp/buildx
    - docker build --platform=local -o . /tmp/buildx
  artifacts:
    paths:
      - buildx
    expire_in: 1 hour

before_script:
  - mkdir -p ~/.docker/cli-plugins
  - mv buildx ~/.docker/cli-plugins/docker-buildx
  - apk add --no-cache build-base git

.build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - make buildx EXTRA_OPTS="--pull --load --platform=${PLATFORM}"

.test:
  image: docker:latest
  stage: test
  services:
    - docker:dind
  script:
    - make buildx test EXTRA_OPTS="--pull --load --platform=${PLATFORM}"

.deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - echo "${REGISTRY_PASSWORD}" | docker login -u "${REGISTRY_USER}" --password-stdin "${REGISTRY_URL}"
    - make buildx REGISTRY="${REGISTRY_URL}" EXTRA_OPTS="--pull --push --platform=linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6"
  only:
    - master

linux/amd64:
  extends: .test
  variables:
    PLATFORM: linux/amd64

linux/arm64:
  extends: .test
  variables:
    PLATFORM: linux/arm64

linux/ppc64le:
  extends: .test
  variables:
    PLATFORM: linux/ppc64le

linux/s390x:
  extends: .test
  variables:
    PLATFORM: linux/s390x

linux/arm/v7:
  extends: .test
  variables:
    PLATFORM: linux/arm/v7

linux/arm/v6:
  extends: .test
  variables:
    PLATFORM: linux/arm/v6

deploy:
  extends: .deploy
  variables:
    REGISTRY_URL: ${CI_REGISTRY}
    REGISTRY_USER: ${CI_REGISTRY_USER}
    REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD}

external:
  extends: .deploy
  variables:
    REGISTRY_URL: ${EXTERNAL_REGISTRY}
    REGISTRY_USER: ${EXTERNAL_REGISTRY_USER}
    REGISTRY_PASSWORD: ${EXTERNAL_REGISTRY_PASSWORD}
